name: gripable_test_app
description: A test application for gripable test

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  animated_button: ^0.2.0
  connectivity_plus: "^1.0.1"
  firebase_auth: "^1.2.0"
  firebase_core: ^1.2.0
  firebase_database: ^7.0.0
  provider: ^5.0.0
  cloud_firestore: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
